import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner/banner";
import Card from "../components/card/card";
import SectionCards from "../components/card/sectionCards";
import NavBar from "../components/navbar/navbar";
import getVideos from "../lib/videos";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  const disneyVideos = await getVideos("modern disney trailer");
  const travelVideos = await getVideos("travel");
  const productivityVideos = await getVideos("productivity");
  // const popularVideos = await getVideos("travel");
  return { props: { disneyVideos, travelVideos, productivityVideos } };
}

export default function Home({
  disneyVideos,
  travelVideos,
  productivityVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="markmaksi@icloud.com" />
      <Banner
        title="Charlie and the Chocolate Factory"
        subTitle="Alesseria's Favourite movie"
        imgUrl="/static/chocolate-factor.jpg"
      />

      <div className={styles.sectionWrapper}>
        <SectionCards
          title="Disney"
          videos={disneyVideos}
          size="large"
        ></SectionCards>

        <SectionCards
          title="Travel"
          videos={travelVideos}
          size="small"
        ></SectionCards>

        <SectionCards
          title="Productivity"
          videos={productivityVideos}
          size="medium"
        ></SectionCards>

        {/* <SectionCards
          title="popular"
          videos={disneyVideos}
          size="small"
        ></SectionCards> */}
      </div>
    </div>
  );
}
