import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner/banner";
import Card from "../components/card/card";
import NavBar from "../components/navbar/navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="markmaksi@icloud.com" />
      <Banner
        title="Charlie and the Chocolate Factory"
        subTitle="Alesseria's Favourite movie"
        imgUrl="/static/chocolate-factor.jpg"
      />
      <Card
        imgUrl="/static/chocolate-factor.jpg"
        size="large"
        priority={true}
      />
      <Card imgUrl="/static/chocolate-factors.jpg" size="medium" />
      <Card imgUrl="/static/chocolate-factors.jpg" size="small" />
    </div>
  );
}
